name: formation-node
services:

  postgres:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: