name: formation-node
services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: